Replace this config (config/importer.yml) with the one from 1Password at:

  https://start.1password.com/open/i?a=NBK7D7DZW5BBBFYVCOK55GXMOE&v=rh6dpuz7h6t3dsae4j5eccqevy&i=qkdo5btti3gvnarzfwqjraxyou&h=mozilla.1password.com

# AUTOMATION_TAG_REPLACE_README_CONFIG
